// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnA6cxLKLHWY1UMFL1pEeLXWzKTXkyzA',
    appId: '1:164725067636:web:346f5e47a940fa78a4a621',
    messagingSenderId: '164725067636',
    projectId: 'erlebnis-radar',
    authDomain: 'erlebnis-radar.firebaseapp.com',
    storageBucket: 'erlebnis-radar.firebasestorage.app',
    measurementId: 'G-8VH2RJGXGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcsr44usZII8rTj7lf8z_v6pR0_D6Rfo4',
    appId: '1:164725067636:android:7a773059edbf3067a4a621',
    messagingSenderId: '164725067636',
    projectId: 'erlebnis-radar',
    storageBucket: 'erlebnis-radar.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlhUzxlnKI6bfQky8AEKB8C3BQVcgOQEg',
    appId: '1:164725067636:ios:3a09866b0dd9e1f6a4a621',
    messagingSenderId: '164725067636',
    projectId: 'erlebnis-radar',
    storageBucket: 'erlebnis-radar.firebasestorage.app',
    iosBundleId: 'de.erlebnisradar.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlhUzxlnKI6bfQky8AEKB8C3BQVcgOQEg',
    appId: '1:164725067636:ios:31bb8e1dec550493a4a621',
    messagingSenderId: '164725067636',
    projectId: 'erlebnis-radar',
    storageBucket: 'erlebnis-radar.firebasestorage.app',
    iosBundleId: 'com.example.schuetzenfestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwnA6cxLKLHWY1UMFL1pEeLXWzKTXkyzA',
    appId: '1:164725067636:web:8c34839200dd8cc6a4a621',
    messagingSenderId: '164725067636',
    projectId: 'erlebnis-radar',
    authDomain: 'erlebnis-radar.firebaseapp.com',
    storageBucket: 'erlebnis-radar.firebasestorage.app',
    measurementId: 'G-Q4SVP2TG0B',
  );
}
