// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlspl4EU2LOOpPuQxKrCe0SZJMY66In14',
    appId: '1:66726540458:web:52df7913bc511c63cdccd3',
    messagingSenderId: '66726540458',
    projectId: 'schuetzenfest-app',
    authDomain: 'schuetzenfest-app.firebaseapp.com',
    storageBucket: 'schuetzenfest-app.firebasestorage.app',
    measurementId: 'G-9YRF5QL0FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE3onF4JT69OeL6nDKJPhNNVHDT1J6AM8',
    appId: '1:66726540458:android:e7f5601531cbd446cdccd3',
    messagingSenderId: '66726540458',
    projectId: 'schuetzenfest-app',
    storageBucket: 'schuetzenfest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_a919u4H1JGH44gfoZprXl4MBWrED6M',
    appId: '1:66726540458:ios:ed6f9235bb61feaacdccd3',
    messagingSenderId: '66726540458',
    projectId: 'schuetzenfest-app',
    storageBucket: 'schuetzenfest-app.firebasestorage.app',
    iosBundleId: 'com.example.schuetzenfestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_a919u4H1JGH44gfoZprXl4MBWrED6M',
    appId: '1:66726540458:ios:ed6f9235bb61feaacdccd3',
    messagingSenderId: '66726540458',
    projectId: 'schuetzenfest-app',
    storageBucket: 'schuetzenfest-app.firebasestorage.app',
    iosBundleId: 'com.example.schuetzenfestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlspl4EU2LOOpPuQxKrCe0SZJMY66In14',
    appId: '1:66726540458:web:3fa646f86d93f368cdccd3',
    messagingSenderId: '66726540458',
    projectId: 'schuetzenfest-app',
    authDomain: 'schuetzenfest-app.firebaseapp.com',
    storageBucket: 'schuetzenfest-app.firebasestorage.app',
    measurementId: 'G-L6CJ4HNRTK',
  );
}
