// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyJS3kuGiJdbAOci34y__AYBQkO-r6MkU',
    appId: '1:33287523144:web:c3d1062777c4341814417d',
    messagingSenderId: '33287523144',
    projectId: 'event-radar-f0b2e',
    authDomain: 'event-radar-f0b2e.firebaseapp.com',
    storageBucket: 'event-radar-f0b2e.firebasestorage.app',
    measurementId: 'G-Q5LTZ2G5QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16uGxXb8pcIRC-JkABpDH22LTByuz0Ak',
    appId: '1:33287523144:android:3823a8a0ea0399f114417d',
    messagingSenderId: '33287523144',
    projectId: 'event-radar-f0b2e',
    storageBucket: 'event-radar-f0b2e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw90Ng6puskX0EezDz2GcMWj6vIpNRoU4',
    appId: '1:33287523144:ios:39cff6fdce696d8814417d',
    messagingSenderId: '33287523144',
    projectId: 'event-radar-f0b2e',
    storageBucket: 'event-radar-f0b2e.firebasestorage.app',
    iosBundleId: 'de.eventradar.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw90Ng6puskX0EezDz2GcMWj6vIpNRoU4',
    appId: '1:33287523144:ios:8708dbea7c77976514417d',
    messagingSenderId: '33287523144',
    projectId: 'event-radar-f0b2e',
    storageBucket: 'event-radar-f0b2e.firebasestorage.app',
    iosBundleId: 'com.example.schuetzenfestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyJS3kuGiJdbAOci34y__AYBQkO-r6MkU',
    appId: '1:33287523144:web:7043818f8879477a14417d',
    messagingSenderId: '33287523144',
    projectId: 'event-radar-f0b2e',
    authDomain: 'event-radar-f0b2e.firebaseapp.com',
    storageBucket: 'event-radar-f0b2e.firebasestorage.app',
    measurementId: 'G-C21EVFR7D1',
  );
}
